[workspace]
members = [
    "framework",
    "debug-tools",
]

[patch.crates-io]
embedded-graphics = { git = "https://github.com/embedded-graphics/embedded-graphics.git"}
embedded-graphics-simulator = { git = "https://github.com/embedded-graphics/simulator.git"}
