[package]
name = "debug-toolsexamples"
version = "0.1.0"
authors = ["Ralf Fuest <mail@rfuest.de>"]
edition = "2021"
publish = false

[dependencies]
framework = { path = "../framework" }
embedded-graphics.workspace = true
embedded-graphics-simulator.workspace = true
