[package]
name = "framework"
version = "0.1.0"
authors = ["Ralf Fuest <mail@rfuest.de>"]
edition = "2021"
publish = false

[dependencies]
embedded-graphics.workspace = true
embedded-graphics-simulator.workspace = true
